area/docs:
- changed-files:
  - any-glob-to-any-file:
    - "*.md"
    - "site/**/*.md"

area/ci:
- changed-files:
  - any-glob-to-any-file:
    - ".github/**/*"

component/ui:
- changed-files:
  - any-glob-to-any-file:
    - "site/src/**/*"
    - "site/gatsby-*.js"
    - "site/package.json"
    - "site/package-lock.json"

component/extensions:
- changed-files:
  - any-glob-to-any-file:
    - "build/**/*"
    - "site/**/*"
    - "Makefile"
    - "script.sh"
